on: push
name: CI
jobs:
  phpunit:
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.1

    services:
      mysql:
        image: mysql:8.0.31
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Install composer dependencies
        run: |
          composer install --no-scripts

      - name: Install NPM dependencies
        run: |
          npm install

      - name: Build NPM dependencies
        run: |
          npm run build

      - name: Prepare Laravel Application
        env:
          HYPIXEL_API_KEY: ${{ secrets.HYPIXEL_API_KEY }}
        run: |
          cp .env.ci .env
          php artisan key:generate
          php artisan migrate
          php artisan db:seed --class=ProfileTableSeeder
          php artisan mock:api

      - name: Run Testsuite
        run: vendor/bin/phpunit tests/

      - name: Run opinionated code styling
        run: ./vendor/bin/pint --test
